busa: &busa
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  database: busa
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *busa

test:
  <<: *busa

production:  
  <<: *busa
  database: busa_production
  username: busa
  password: r3mind3r
