busa: &busa
  adapter: postgis
  postgis_extension: true
  schema_search_path: public,postgis
  database: busa
  user: postgres
  password: password
  pool: 5
  timeout: 5000
  host: localhost
  template: template1

development:
  <<: *busa

test:
  <<: *busa

production:  
  <<: *busa
  database: busa_production
  username: busa
  password: r3mind3r
